/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.koichatapp;

import cvt.chat.component.ChatBox;
import cvt.chat.model.ModelMessage;
import cvt.chat.swing.ChatEvent;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.AbstractBorder;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author CVT
 */
public class ChatUI extends javax.swing.JFrame {
    SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy, hh:mmaa");
    /**
     * Creates new form ChatUI
     */
    public ChatUI() {
        initComponents();
        Icon icon = new ImageIcon(getClass().getResource("\\Imgs\\27.png"));
        Icon icon2 = new ImageIcon(getClass().getResource("\\Imgs\\33.png"));
        String date = df.format(new Date());
        this.sideBarMain.addChatBox(new ModelMessage(icon, "CVT", date, "Châu Thịnh"));
        this.sideBarMain.addChatBox(new ModelMessage(icon2, "VD", date, "Vũ Đạt"));
        this.sideBarMain.addChatBox(new ModelMessage(icon, "CVT", date, "Châu Thịnh"));
        this.sideBarMain.addChatBox(new ModelMessage(icon2, "VD", date, "Vũ Đạt"));
        this.sideBarMain.addChatBox(new ModelMessage(icon, "CVT", date, "Châu Thịnh"));
        this.sideBarMain.addChatBox(new ModelMessage(icon2, "VD", date, "Vũ Đạt"));
        this.sideBarMain.addChatBox(new ModelMessage(icon, "CVT", date, "Châu Thịnh"));
        this.sideBarMain.addChatBox(new ModelMessage(icon2, "VD", date, "Vũ Đạt"));
        this.sideBarMain.addChatBox(new ModelMessage(icon, "CVT", date, "Châu Thịnh"));
        this.sideBarMain.addChatBox(new ModelMessage(icon2, "VD", date, "Vũ Đạt"));
        this.sideBarMain.addChatBox(new ModelMessage(icon, "CVT", date, "Châu Thịnh"));
        this.sideBarMain.addChatBox(new ModelMessage(icon2, "VD", date, "Vũ Đạt"));
        this.sideBarMain.addChatBox(new ModelMessage(icon, "CVT", date, "Châu Thịnh"));
        this.sideBarMain.addChatBox(new ModelMessage(icon2, "VD", date, "Vũ Đạt"));
        this.sideBarMain.addChatBox(new ModelMessage(icon, "CVT", date, "Châu Thịnh"));
        this.sideBarMain.addChatBox(new ModelMessage(icon2, "VD", date, "Vũ Đạt"));
        load();
    }
    
    private void load() {
        Dimension desktopsize = this.getSize();
        chatAreaCur.setTitle("Châu Thịnh");
        chatAreaCur.addChatEvent(new ChatEvent() {
            @Override
            public void mousePressedSendButton(ActionEvent evt) {
                Icon icon = new ImageIcon(getClass().getResource("\\Imgs\\27.png"));
                String name = "Tôi là ai";
                String date = df.format(new Date());
                String message = chatAreaCur.getText().trim();
                chatAreaCur.addChatBox(new ModelMessage(icon, name, date, message), ChatBox.BoxType.RIGHT);
                chatAreaCur.addChatBox(new ModelMessage(new ImageIcon(getClass().getResource("\\Imgs\\33.png")), "Bạn là ai", df.format(new Date()), "Ăn nói xà lơ"), ChatBox.BoxType.LEFT);
                chatAreaCur.clearTextAndGrabFocus();
            }

            @Override
            public void mousePressedFileButton(ActionEvent evt) {
                
            }

            @Override
            public void keyTyped(KeyEvent evt) {
                
            }
            
        });
        System.out.println(desktopsize.width);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundCur = new cvt.chat.swing.Background();
        chatAreaCur = new cvt.chat.component.ChatArea();
        sideBarMain = new cvt.chat.component.SideBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        backgroundCur.setBackground(new java.awt.Color(255, 255, 255));
        backgroundCur.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout backgroundCurLayout = new javax.swing.GroupLayout(backgroundCur);
        backgroundCur.setLayout(backgroundCurLayout);
        backgroundCurLayout.setHorizontalGroup(
            backgroundCurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundCurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sideBarMain, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chatAreaCur, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundCurLayout.setVerticalGroup(
            backgroundCurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundCurLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundCurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sideBarMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chatAreaCur, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundCur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundCur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ChatUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private cvt.chat.swing.Background backgroundCur;
    private cvt.chat.component.ChatArea chatAreaCur;
    private cvt.chat.component.SideBar sideBarMain;
    // End of variables declaration//GEN-END:variables
}
